### ISSUE TITLE
H/A failure on management servers

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/mainnet-outage#10]
| Questions       |        Needed Information....................................|
| ------------- |:----------------------------------------------:|
| Date                        |   09/04/2023                                                                    |
| Outage Type          |  Interruption -- redundancy                                                                     |
| Nature of Problem | H/A                                                                      |
| Time Down             |  Zero                                                                     |
| Time Restored       |   30 minutes                                                                    |
| Site                         |  Mainnet                                                                     |
| Operator                |  Bill Keuntje                                                                     |
| Current Stat          |                                                                       |
| Action Taken         | Cluster backup server restart                                                                       |

**Comment by Bill-Kunj** [comment]
Time down should be HH:MM:SS instead of a duration

**Comment by Bill-Kunj** [comment]
@jetman2 @SteveHenley Can this issue be closed?

**Comment by DPMBarnes** [comment]
Completed
