### ISSUE TITLE
Local host in alert links

### ISSUE THREAD

**Issue by DPMBarnes** [rchain-community/mainnet-outage#14]
Alert's show "local Host" not public facing name.

**Comment by Bill-Kunj** [comment]
Example alert with bad links

Source: http://localhost:3000/alerting/grafana/98xzTuYVz/view
Silence: http://localhost:3000/alerting/silence/new?alertmanager=grafana&matcher=alertname%3Ddisk_space_alert&matcher=datacenter%3Dhz-de&matcher=disk%3D%2Fdev%2Fsda1&matcher=grafana_folder%3DDisk+Space&matcher=instance%3D10.4.1.101%3A4646&matcher=job%3Dnomad_metrics&matcher=node_class%3Dnone&matcher=node_id%3D7597a231-4d5b-c225-3bd1-2292091ac35e&matcher=node_scheduling_eligibility%3Deligible&matcher=node_status%3Dready

**Comment by DPMBarnes** [comment]
Possibly Dan and/or Andrew and/or David.

**Comment by DPMBarnes** [comment]
Fixed.
GF_SERVER_ROOT_URL=<Web Link> to docker run command.

Ref: https://discord.com/channels/1068875609935204464/1068878431569330206/1113828264163676251

**Comment by Bill-Kunj** [comment]
The code fix was to add a script to set the value of GF_SERVER_ROOT_URL in the environment.
