### ISSUE TITLE
Create L1 training road map

### ISSUE THREAD

**Issue by DPMBarnes** [rchain-community/mainnet-outage#20]
Needed for current L1 staff as well as onboarding new people. @Bill-Kunj was looking into this. @DPMBarnes to take over this task.

**Comment by Bill-Kunj** [comment]
@DPMBarnes Please update this issue and close if the current on-boarding process by @SteveHenley is sufficient.

**Comment by DPMBarnes** [comment]
Included in @SteveHenley on-boarding
