### ISSUE TITLE
Incomplete README.md Documentation

### ISSUE THREAD

**Issue by David405** [rchain-community/mainnet-outage#21]
The README.md tries to describe the template keywords for setting up an AAR, however, a couple of keywords are missing.

ACTION PLAN - Improve the documentation by adding a glossary of all keywords present in the AAR.

**Comment by Bill-Kunj** [comment]
@David405 Please review the updates to `README.md` and push this issue to completion

**Comment by DPMBarnes** [comment]
Readme.md updated
