### ISSUE TITLE
Mainnet Outage - 5th June 2023

### ISSUE THREAD

**Issue by zsluedem** [rchain-community/mainnet-outage#26]
| Questions       |        Needed Information     |
| ------------- |:----------------------------------------------:|
| Date                  |                   5th June 2023                     |
| Outage Type           |                      Long term                  |
| Nature of Problem     |                     hz-de-private-rhob-02 is down                   |
| Time Circuit Went Down     |         4:22am UTC                                 |
| Time Circuit Was Restored |         7:17am UTC                              |
| Site                  |                mainnet                       |
| Operator              |            @zsluedem                             |
| Current Status        |             Fixed                           |
| Action Taken          |                   Reboot hz-de-private-rhob-02 and it is fixed                     |

**Comment by DPMBarnes** [comment]
Completed info about issue
