### ISSUE TITLE
Unexpected Error - observer down

### ISSUE THREAD

**Issue by JayeshNaphade** [rchain-community/mainnet-outage#33]
| Questions       |        Needed Information     |
| ------------- |:----------------------------------------------:|
| Date                  |        June 20/2023                                |
| Outage Type           |     Rchain developer interface explore check balance is not working.Unexpected error while capturing results from Rholang: java.lang.RuntimeException: unknown rootWallet Outage deploy explore fails.                                   |
| Nature of Problem     |    TBD                                   |
| Time Circuit Went Down     |         DD: 20   HH:0900    MM:47                                 |
| Time Circuit Was Restored |         DD:    HH:    MM:                                 |
| Site                  |     (https://rholang.io/oc-mainnet-wallet/)                                  |
| Operator              |     Hetzner                                   |
| Current Status        |     Down                                   |
| Action Taken          |      Explore Test                                   |

**Comment by Bill-Kunj** [comment]
Fixed: rebooted traefik and observers.

**Comment by JayeshNaphade** [comment]
![Screenshot (129)](https://github.com/rchain-community/mainnet-outage/assets/126679415/e9c3838b-9db3-4b63-9cb2-b2552a5f515c)
Rchain developer interface explore check balance is not working and the oc-mainnet-wallet is also giving an error.

**Comment by Bill-Kunj** [comment]
> Rchain developer interface explore check balance is not working and the oc-mainnet-wallet is also giving an error.

Please provide procedure to reproduce the error

**Comment by Bill-Kunj** [comment]
I note that the dropdown menus include testnet, which hasn't existed in many months. It seems the software for the wallet is intolerably out-of-date.

Selecting a mainnet server from the dropdown and clicking on status provides a correct response from the observer. Maybe something is wrong with your wallet code?

https://observer.services.mainnet.rchain.coop/status

**Comment by jimscarver** [comment]
the Asian observer is working fine, so  we are not down completly.
![image](https://github.com/rchain-community/mainnet-outage/assets/3037201/99ff1415-cd77-4922-a9b2-a057d2c4023f)

**Comment by azazime** [comment]
The Observer node needs to be restarted

**Comment by Bill-Kunj** [comment]
There is now a casper failure on `observer.services.mainnet.rchain.coop`.  L3 is working the problem

**Comment by Bill-Kunj** [comment]
@JayeshNaphade @jimscarver I note that your screenshots include `https://rholang.io/oc-mainnet-wallet/`.
I thought the `mainnet` wallet was running elsewhere. What is `rholang.io`, and why are the testnet servers listed in the dropdowns?
This really looks like a non-RevDev wallet

**Comment by Bill-Kunj** [comment]
Reviewing the history, it appears the observer ran out of memory about a week ago. Which probably isn't possible under normal operation.
The `observer` is NOT *down*, but it is operating with a casper failure

**Comment by Bill-Kunj** [comment]
https://observer.services.mainnet.rchain.coop/api/blocks is now functional.

Please retest your failure scenario and close if all is fixed @JayeshNaphade

**Comment by JayeshNaphade** [comment]
I have tested the failure scenario thoroughly, and the issue has been resolved completely. I have verified the fix and can confirm that everything is functioning as expected. Therefore, I am closing the issue now.
