### ISSUE TITLE
Bad links in grafana exhibition dashboard

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/mainnet-outage#49]
On the grafana dashboard http://167.235.8.82:3000/d/4NYOvS-7zj/all-in-one?orgId=1, the links under the "cluster" panel point to https://mon.cinarra.com, which is not our server. I'm guessing these links will not work properly

It would be better if these links pointed to our own grafana server and resources

**Comment by robin0904** [comment]
Hello Team, I have added the proper link on Dashboard now issue is Resolved. Hence Closing the ticket. 

Thank you!
