### ISSUE TITLE
Block creation stopped at 1800639 - Outage 2023/04/01

### ISSUE THREAD

**Issue by Strecoza33** [rchain-community/mainnet-outage#5]
Revdefine shows block creation stopped at approx 10:40pm ET. Last block created was 1800639.

DevOps Response - There has been a networking hardware failure in the hetzner datacenter. In response, Nomad has migrated two validators to a different hetzner datacenter. Those migrated validators are catching back up with the network by retrieving missing blocks. This is normal, expected recovery behavior from a network hardware failure
It may be a couple of hours before the network is "whole" again.

**Comment by Bill-Kunj** [comment]
Networking outage in a Hetzner-owned network switch at 2023-04-02, 02:24 AM UTC.

https://status.hetzner.com/incident/955f29d2-cc92-44a8-b168-f59a64091c26

This caused Nomad to (correctly) migrate the two affected systems to spare capacity in a different datacenter.
As a result, the validators that were moved onto spare systems needed to catch up with the rest of the network. This was completed at 2023-04-02, 04:18 AM UTC.

The Hetzner network failure was resolved at 2023-04-02, 03:05 AM UTC, and the IT infrastructure is now back to normal.

@Strecoza33 Please review this report for accuracy and completeness before closing
