### ISSUE TITLE
L1 Monitoring Dasboarding and Alerting Outstanding Items

### ISSUE THREAD

**Issue by ally2211** [rchain-community/mainnet-outage#53]
Create a playlist of dashboards on any given tag.
-  Request is made that anyone who has created a dashboard in general folders like exhibition or L1 Monitoring that they add descriptive tags including any variation of the following:  Health Status, Client Status,  Jobs, Allocations, CPU, Memory, Raft, Vault.
Once your dashboard is tagged (go to dashboard settings) we can then create a playlist of dashboards when presenting or when troubleshooting that will select your dashboard.
 
- update alerts with a panel link and a more detailed description.

- add Raft alert.

**Comment by Bill-Kunj** [comment]
@ally2211 These are not closely connected items. Can you separate into individual github issues and close this?
