### ISSUE TITLE
Need Dashboards which are easy-to-understand for the customers.

### ISSUE THREAD

**Issue by JayeshNaphade** [rchain-community/mainnet-outage#63]
We need dashboards which shows single-value pannel that shows a single red/amber/green number pannel for customers.

**Comment by kosh000** [comment]
For Complaints (Non-Existent Outages):
We need a public dashboard for customers who complain or who are unable to navigate on Grafana.

**Comment by JayeshNaphade** [comment]
Working on it.

**Comment by JayeshNaphade** [comment]
http://grf-00.elisa.revdev.world:3000/d/af213cb2-837f-4488-8d1d-0499a6a393dd/customer-based?orgId=1&from=1695370987952&to=1695392587952 
Customer based dashboard is created.
